// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojszsglrzzfeobayntdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qc3pzZ2xyenpmZW9iYXludGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzQzODEsImV4cCI6MjA1MzgxMDM4MX0.6ZLufkryTuawUtOG7MsPmlFH5HZhuRX3H2h6MByX0hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);